stages:
  - build
  - test
  - release

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind

  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.datadrivendiscovery.org
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN pullregistry.datadrivendiscovery.org

  variables:
    REG_PATH: registry.datadrivendiscovery.org/$CI_PROJECT_PATH
    DOCKER_DRIVER: overlay2

  script:
    - echo "destination image" $REG_PATH/ci:$CI_COMMIT_SHA
    - docker pull "pull"$REG_PATH/d3m_outputs:latest || true
    - docker build --cache-from "pull"$REG_PATH/d3m_outputs:latest --tag $REG_PATH/ci:$CI_COMMIT_SHA  .
    - docker run $REG_PATH/ci:$CI_COMMIT_SHA -h  # display the help message
    - docker push $REG_PATH/ci:$CI_COMMIT_SHA


tests:
  stage: test
  image:
    name: registry.datadrivendiscovery.org/$CI_PROJECT_PATH/ci:$CI_COMMIT_SHA
    entrypoint: [""]
  
  before_script:
    - pip install coverage
  
  script:
    - coverage run --branch --source=./d3m_outputs -m pytest -s test/ -v
    - coverage report -m


branch_release:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.datadrivendiscovery.org

  variables:
    REG_PATH: registry.datadrivendiscovery.org/$CI_PROJECT_PATH
    DOCKER_DRIVER: overlay2

  script:
    - echo "destination images" $REG_PATH/branches/$CI_COMMIT_REF_NAME:latest
    - docker pull $REG_PATH/ci:$CI_COMMIT_SHA
    - docker tag $REG_PATH/ci:$CI_COMMIT_SHA $REG_PATH/branches/$CI_COMMIT_REF_NAME:latest
    - docker push $REG_PATH/branches/$CI_COMMIT_REF_NAME:latest

  # only on non-issue branches
  only:
    - branches
  except:
    - /^issue-.*$/

release:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.datadrivendiscovery.org

  variables:
    REG_PATH: registry.datadrivendiscovery.org/$CI_PROJECT_PATH
    DOCKER_DRIVER: overlay2

  script:
    - echo "destination images" $REG_PATH/d3m_outputs:CI_COMMIT_TAG $REG_PATH/d3m_outputs:latest
    - docker pull $REG_PATH/ci:$CI_COMMIT_SHA
    - docker tag $REG_PATH/ci:$CI_COMMIT_SHA $REG_PATH/d3m_outputs:$CI_COMMIT_TAG
    - docker tag $REG_PATH/ci:$CI_COMMIT_SHA $REG_PATH/d3m_outputs:latest
    - docker push $REG_PATH/d3m_outputs:$CI_COMMIT_TAG
    - docker push $REG_PATH/d3m_outputs:latest

  only:
    - tags
