build:
  image: pullregistry.datadrivendiscovery.org/nist/registry/python:3.6.5-slim

  script:
    - pip install .

  only:
    - refactor

tests:
  image: pullregistry.datadrivendiscovery.org/nist/registry/python:3.6.5-slim

  script:
    - python -m unittest discovery

  only:
    - refactor