image: python:3.6

stages:
  - test
  - quality
  - documentation
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
build:
  stage: test

  before_script:
    - pip install git+https://gitlab.com/datadrivendiscovery/d3m.git@v2018.6.5#egg=d3m
    - pip install -r requirements.txt
    - python setup.py install
    - dval -h
    - pip install pytest coverage
  script:
    - coverage run --source dval -m pytest --junitxml=report.xml
    - coverage report
    - coverage html
  artifacts:
    paths:
      - htmlcov
    reports:
      junit: report*.xml

lint:
  stage: quality
  before_script:
    - pip install tox
  script: tox -e lint

formatting:
  stage: quality
  before_script:
    - pip install tox
  script: tox -e formatting

docs:
  stage: documentation
  dependencies:
    - build
  before_script:
    - pip install git+https://gitlab.com/datadrivendiscovery/d3m.git@v2018.6.5#egg=d3m sphinx sphinx-rtd-theme
    - pip install -r requirements.txt
    - python setup.py install
    - dval -h
  script:
    - mkdir -p docs/_static/coverage
    - cp -r htmlcov/* docs/_static/coverage/
    - sphinx-apidoc -o docs/source/ dval
    - sphinx-build -b html docs/source/ html_docs
  artifacts:
    paths:
    - html_docs


pages:
  stage: deploy
  dependencies:
    - docs
  script:
    - mv html_docs public
  artifacts:
    paths:
      - public
  only:
    - tags
    - master
    - web
