stages:
  - build
  - test
  - release

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind

  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.datadrivendiscovery.org
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN pullregistry.datadrivendiscovery.org

  variables:
    REG_PATH: registry.datadrivendiscovery.org/$CI_PROJECT_PATH
    DOCKER_DRIVER: overlay2

  script:
    - echo "destination image" $REG_PATH/ci:$CI_COMMIT_SHA
    - docker build --tag $REG_PATH/ci:$CI_COMMIT_SHA  .
    - docker push $REG_PATH/ci:$CI_COMMIT_SHA


unittests:
  stage: test
  image:
    name: registry.datadrivendiscovery.org/$CI_PROJECT_PATH/ci:$CI_COMMIT_SHA
    entrypoint: ["/bin/bash", "-c"]
  script:
    - python -m unittest discover


release:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.datadrivendiscovery.org

  variables:
    REG_PATH: registry.datadrivendiscovery.org/$CI_PROJECT_PATH
    DOCKER_DRIVER: overlay2

  script:
    - echo "destination image" $REG_PATH/d3m_outputs:latest
    - docker pull $REG_PATH/ci:$CI_COMMIT_SHA
    - docker tag $REG_PATH/ci:$CI_COMMIT_SHA $REG_PATH/d3m_outputs:latest
    - docker push $REG_PATH/d3m_outputs:latest

  only:
    - master

