stages:
  - test
  - documentation

build:
  stage: test
  image: python:3.6.5

  before_script:
    - pip install pip==9.0.3
    - pip install -r requirements.txt
    - pip install --process-dependency-links git+https://gitlab.com/datadrivendiscovery/d3m.git@v2018.6.5#egg=d3m
    - python setup.py install
    - d3m_outputs -h
    - python -m pip install coverage
  script:
    - coverage run --branch --source=./d3m_outputs -m pytest -s test/ -v && coverage report -m && coverage html
  artifacts:
    paths:
      - $CI_PROJECT_DIR/htmlcov


pages:
  stage: documentation
  
  script:
  - pip install sphinx sphinx-rtd-theme
  - cd docs
  - sphinx-apidoc -o source/ ../d3m_outputs
  - sphinx-build -b html source/ build/
  - mv build/ ../public/
  artifacts:
    paths:
    - public

  only:
    - tags
