stages:
  - build
  - test
  - release

build:
  stage: build
  
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.datadrivendiscovery.org
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN pullregistry.datadrivendiscovery.org

  variables:
    REG_PATH: registry.datadrivendiscovery.org/$CI_PROJECT_PATH
    DOCKER_DRIVER: overlay2

  script:
    - echo "destination image" $REG_PATH/ci:$CI_COMMIT_SHA
    - docker build --tag $REG_PATH/ci:$CI_COMMIT_SHA  .
    - docker run $REG_PATH/ci:$CI_COMMIT_SHA -h  # display the help message
  tags:
    - shell

tests:
  stage: test
  image:
    name: $REG_PATH/ci:$CI_COMMIT_SHA
    entrypoint: [""]
  
  before_script:
    - pip install coverage
  
  script:
    - coverage run --branch --source=./d3m_outputs -m pytest -s test/ -v
    - coverage report -m


branch_release:
  stage: release
  
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.datadrivendiscovery.org

  variables:
    REG_PATH: registry.datadrivendiscovery.org/$CI_PROJECT_PATH
    DOCKER_DRIVER: overlay2

  script:
    - echo "destination images" $REG_PATH/branches/$CI_COMMIT_REF_NAME:latest
    - docker tag $REG_PATH/ci:$CI_COMMIT_SHA $REG_PATH/branches/$CI_COMMIT_REF_NAME:latest
    - docker push $REG_PATH/branches/$CI_COMMIT_REF_NAME:latest

  # only on develop and master branches
  only:
    - master
    - develop
  tags:
    - shell

release:
  stage: release
  
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.datadrivendiscovery.org

  variables:
    REG_PATH: registry.datadrivendiscovery.org/$CI_PROJECT_PATH
    DOCKER_DRIVER: overlay2

  script:
    - echo "destination images" $REG_PATH/d3m_outputs:CI_COMMIT_TAG $REG_PATH/d3m_outputs:latest
    - docker tag $REG_PATH/ci:$CI_COMMIT_SHA $REG_PATH/d3m_outputs:$CI_COMMIT_TAG
    - docker tag $REG_PATH/ci:$CI_COMMIT_SHA $REG_PATH/d3m_outputs:latest
    - docker push $REG_PATH/d3m_outputs:$CI_COMMIT_TAG
    - docker push $REG_PATH/d3m_outputs:latest
  tags:
    - shell

  only:
    - tags
