image: python:3.6

stages:
  - test
  - quality
  - documentation
  - deploy

build:
  stage: test

  before_script:
    - pip install pip==9.0.3
    - pip install -r requirements.txt
    - pip install --process-dependency-links git+https://gitlab.com/datadrivendiscovery/d3m.git@v2018.6.5#egg=d3m
    - python setup.py install
    - d3m_outputs -h
    - pip install pytest coverage
  script:
    - coverage run --source d3m_outputs -m pytest --junitxml=report.xml
    - coverage report
    - coverage html
  artifacts:
    paths:
      - htmlcov
    reports:
      junit: report*.xml

lint:
  stage: quality
  before_script:
    - pip install tox
  script: tox -e lint

formatting:
  stage: quality
  before_script:
    - pip install tox
  script: tox -e formatting

docs:
  stage: documentation
  dependencies:
    - build
  script:
    - mkdir -p docs/_static/coverage
    - cp -r htmlcov/* docs/_static/coverage/
    - pip install tox
    - tox -e docs
  artifacts:
    paths:
    - html_docs


pages:
  stage: deploy
  dependencies:
    - docs
  script:
    - mv html_docs public
  artifacts:
    paths:
      - public
  only:
    - tags
